### ISSUE TITLE
Is there a way to reload / update logging configuration at runtime?

### ISSUE THREAD

**Issue by ieugen** [amperity/dialog#23]
Is there a way to update the logging configuration / levels at runtime without restarting the app?

I imagine this to be useful during long REPL sessions or even in production.

Is there a way to to the same by reloading the config on disk?
This is for OPS where no repl is available / desired. 

In unix ops the process is usually:
* send the app a SIGUSR signal 
* the app will read the file on disk and apply the configuration without downtime / connection closing.

I think for dialog is enough to implement logic to apply configuration changes.
Loading can happen on the client side.

**Comment by greglook** [comment]
Yes, you can call `dialog.logger/initialize!` to reload the configuration wholesale:
https://github.com/amperity/dialog/blob/10a22a24d4d21b8eb56fe08df3bf0843e2d75c22/src/clojure/dialog/logger.clj#L49-L51

To manage individual logger levels at runtime, use `dialog.logger/set-level!`
https://github.com/amperity/dialog/blob/10a22a24d4d21b8eb56fe08df3bf0843e2d75c22/src/clojure/dialog/logger.clj#L143-L146

We expose this as part of an administrative endpoint on our service instances, which also supports things like health checks and graceful shutdowns.

**Comment by ieugen** [comment]
Configuration can be altered at runtime in two ways: 

* reload the whole configuration file and apply changes via `dialog.logger/initialize!` 
* set a logger value via `dialog.logger/set-level!`

```clojure
  ;; see current configuration
  log/config

  (log/initialize!)
  (dialog.logger/set-level! "dev.start" :debug)
  (dialog.logger/debug "Dialog info")
  (clojure.tools.logging/debug "tools.logging info")
  (dialog.logger/set-level! "dev.start" :info)
  (dialog.logger/debug "Dialog info")
  (clojure.tools.logging/debug "tools.logging info")

  (dialog.logger/set-level! "com.zaxxer.hikari.util.DriverDataSource" :info)
```

**Comment by ieugen** [comment]
Tooling for doing this at runtime can be constructed as an external functionality using these primitives.
