### ISSUE TITLE
default dependency to org.slf4j/log4j-over-slf4j ?

### ISSUE THREAD

**Issue by behrica** [amperity/dialog#32]
Any reason that this bridge is not included ?

I would hope to get a "once-for-ever" solution which bridges everything into "slf4j"

**Comment by greglook** [comment]
I hadn't originally included it since our use-case (Spark) uses log4j in parallel with dialog via slf4j, but that's probably uncommon. I think we could just exclude the log4j bridge if it was included by default, so this seems like a good change.

**Comment by greglook** [comment]
Part of the default dependencies in 2.0.115.
